export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const RESTAURANT_REPOSITORY = Symbol('RESTAURANT_REPOSITORY');
export const SECTION_REPOSITORY = Symbol('SECTION_REPOSITORY');
export const TABLE_REPOSITORY = Symbol('TABLE_REPOSITORY');
export const IMAGE_REPOSITORY = Symbol('IMAGE_REPOSITORY');
export const RESERVATION_REPOSITORY = Symbol('RESERVATION_REPOSITORY');
export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');
export const REVIEW_REPOSITORY = Symbol('REVIEW_REPOSITORY');
export const SUBSCRIPTION_REPOSITORY = Symbol('SUBSCRIPTION_REPOSITORY');
export const SUBSCRIPTION_PLAN_REPOSITORY = Symbol(
  'SUBSCRIPTION_PLAN_REPOSITORY',
);
export const MENU_REPOSITORY = Symbol('MENU_REPOSITORY');
export const DISH_REPOSITORY = Symbol('DISH_REPOSITORY');
export const LAYOUT_OBJECT_REPOSITORY = Symbol('LAYOUT_OBJECT_REPOSITORY');

